---
# tasks file for ping_test role
- name: Linux Ping Test
  block:
    - name: Ping managed host
      ansible.builtin.ping:
      register: ping_result

    - name: Capture Execution Details (Success)
      ansible.builtin.include_role:
        name: execution_result
      vars:
        execution_result_return_code: "{{ ping_result.rc | default(0) }}"
        execution_result_message: "{{ ping_result.stderr | default('Unknown error') }}"
        execution_result_failed_task: "Run the primary task"
  rescue:
    - name: Capture Execution Details (Failure)
      ansible.builtin.include_role:
        name: execution_result
      vars:
        execution_result_return_code: "{{ ping_result.rc | default(1) }}"
        execution_result_message: "{{ ping_result.stderr | default('Unknown error') }}"
        execution_result_failed_task: "Run the primary task"

# - name: Windows Ping Test
#   block:
#     - name: Ping managed host
#       ansible.builtin.win_ping:
#       register: ping_result

#     - name: Capture Execution Details (Success)
#       ansible.builtin.include_role:
#         name: execution_result
#       vars:
#         execution_result_return_code: "{{ ping_result.rc | default(0) }}"
#         execution_result_message: "{{ ping_result.stderr | default('Unknown error') }}"
#         execution_result_failed_task: "Run the primary task"
#   rescue:
#     - name: Capture Execution Details (Failure)
#       ansible.builtin.include_role:
#         name: execution_result
#       vars:
#         execution_result_return_code: "{{ ping_result.rc | default(1) }}"
#         execution_result_message: "{{ ping_result.stderr | default('Unknown error') }}"
#         execution_result_failed_task: "Run the primary task"
