---
- name: Gather Operating System Details
  block:
    - name: Collect OS facts
      ansible.builtin.setup:
        gather_subset:
          - '!all'
          - '!min'
          - 'distribution'
          - 'platform'

    - name: Display Operating System Information
      ansible.builtin.debug:
        msg:
          - "Operating System: {{ ansible_distribution | default('Unknown') }}"
          - "OS Version: {{ ansible_distribution_version | default('Unknown') }}"
          - "OS Family: {{ ansible_os_family | default('Unknown') }}"
          - "System: {{ ansible_system | default('Unknown') }}"
          - "Architecture: {{ ansible_architecture | default('Unknown') }}"
          - "Hostname: {{ ansible_hostname | default('Unknown') }}"

- name: Linux Ping Test
  block:
    - name: Ping managed host
      ansible.builtin.ping:
      register: ping_result

  rescue:
    - name: Capture Execution Details (Failure)
      ansible.builtin.include_role:
        name: execution_result

- name: Windows Ping Test
  block:
    - name: Ping managed host
      ansible.builtin.win_ping:
      register: ping_result

  rescue:
    - name: Capture Execution Details (Failure)
      ansible.builtin.include_role:
        name: execution_result
